server:
  port : ${WEB_SERVER_PORT:17239}

spring:
  liquibase:
    enabled: true
    contexts: "local"
    change-log: classpath:db/changelog/changelog-master.xml
  postgres:
    jdbc-url: ${DB_CONNECTION_STRING:jdbc:postgresql://v:5432/tn-scada-dev}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:PG648642}
    driver-class-name: org.postgresql.Driver
  main:
    allow-bean-definition-overriding: true

application:
  kafka:
    application-id: kafka-clickhouse-connector
    bootstrap-servers: ${BOOTSTRAP_SERVERS_CONFIG:localhost:9093,localhost:9094,localhost:9095}
    schema-registry-url: ${SCHEMA_REGISTRY_URL_CONFIG:http://localhost:8081}
    group-id: kafka-clickhouse-listener
  clickhouse:
    address: ${CLICKHOUSE_HOST:localhost}
    port: ${CLICKHOUSE_PORT:8123}
  in-memory:
    address: ${REDIS_HOST:localhost:6379}
  db:
    address: ${DB_ADDRESS:localhost}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:PG648642}
    port: ${DB_PORT:5432}
    database: ${DB_NAME:db-dev}
